import localFont from "next/font/local";
import "./globals.css";

// 👇 Only Open Sans from /public/fonts
const openSans = localFont({
  src: [
    { path: "./fonts/OpenSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/OpenSans-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/OpenSans-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/OpenSans-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "School Hive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
